packages: 
  - "services/*"

catalog:
  #common
  "vitest": "^2.1.8"
  "@vitest/coverage-v8": "^2.1.8"
  "@biomejs/biome": "2.3.11"

  #frontend
  "next": "16.1.1"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "@tailwindcss/postcss": "^4"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "tailwindcss": "^4"
  "typescript": "^5"

  #backend
  "@nestjs/common": "^11.0.1"
  "@nestjs/core": "^11.0.1"
  "@nestjs/platform-express": "^11.0.1"
  "reflect-metadata": "^0.2.2"
  "rxjs": "^7.8.1"
  "@nestjs/cli": "^11.0.0"
  "@nestjs/schematics": "^11.0.0"
  "@nestjs/testing": "^11.0.1"
  "@types/express": "^5.0.0"
  "@types/jest": "^30.0.0"
  "@types/node": "^22.10.7"
  "@types/supertest": "^6.0.2"
  "jest": "^30.0.0"
  "source-map-support": "^0.5.21"
  "supertest": "^7.0.0"
  "ts-jest": "^29.2.5"
  "ts-loader": "^9.5.2"
  "ts-node": "^10.9.2"
  "tsconfig-paths": "^4.2.0"
