packages:
  - services/*

catalog:
  '@biomejs/biome': 2.3.11
  '@nestjs/cli': ^11.0.0
  '@nestjs/common': ^11.0.1
  '@nestjs/core': ^11.0.1
  '@nestjs/platform-express': ^11.0.1
  '@nestjs/schematics': ^11.0.0
  '@nestjs/testing': ^11.0.1
  '@tailwindcss/postcss': ^4
  '@types/express': ^5.0.0
  '@types/jest': ^30.0.0
  '@types/node': ^22.10.7
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/supertest': ^6.0.2
  '@vitest/coverage-v8': ^2.1.8
  jest: ^30.0.0
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  tailwindcss: ^4
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  typescript: ^5
  unplugin-swc: ^1.5.9
  vitest: ^2.1.8
